### ISSUE TITLE
buil error - node v6.2.1 - (node:93190) fs: re-evaluating native module sources is not supported

### ISSUE THREAD

**Issue by hungvq** [driftyco/ionic-preview-app#33]
Mac:ionic-preview-app hungvq$ ionic build
(node:93190) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
There is an error in your gulpfile: 
Error: Node Sass does not yet support your current environment: OS X 64-bit with false
For more information on which environments are supported please see:
TODO URL
    at Object.<anonymous> (/Users/hungvq/Documents/ionic-preview-app/node_modules/node-sass/lib/index.js:12:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/hungvq/Documents/ionic-preview-app/node_modules/gulp-sass/index.js:175:21)
    at Module._compile (module.js:541:32)

Mac:ionic-preview-app hungvq$ node -v
v6.2.1
Mac:ionic-preview-app hungvq$ npm -v
3.9.3

**Comment by hungvq** [comment]
Solved
npm rebuild node-sass
