### ISSUE TITLE
ionic serve does not work with ionic-gulp-browserify-typescript 1.1.0

### ISSUE THREAD

**Issue by xiongemi** [driftyco/ionic-preview-app#43]
Error

```
Caught exception:
 Error: ENOENT: no such file or directory, lstat '/Users/emilyxiong/Documents/ionic/ionic-preview-app/typings/index.d.ts'
    at Error (native)
    at Object.fs.lstatSync (fs.js:887:18)
    at Object.realpathSync (fs.js:1518:21)
    at /Users/emilyxiong/Documents/ionic/ionic-preview-app/node_modules/tsify/index.js:58:38
    at Array.map (native)
    at DestroyableTransform.flush [as _flush] (/Users/emilyxiong/Documents/ionic/ionic-preview-app/node_modules/tsify/index.js:58:6)
    at DestroyableTransform.<anonymous> (/Users/emilyxiong/Documents/ionic/ionic-preview-app/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:115:49)
    at DestroyableTransform.g (events.js:273:16)
    at emitNone (events.js:80:13)
    at DestroyableTransform.emit (events.js:179:7) 
```

**Comment by xiongemi** [comment]
This should be fixed with pr:
https://github.com/driftyco/ionic-preview-app/pull/44

**Comment by brandyscarney** [comment]
I'm going to close this as it seems you fixed it with https://github.com/driftyco/ionic-preview-app/pull/44. Thanks for the PR! :)
