### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by yozman** [driftyco/ionic-preview-app#63]
i clone the master
then `npm i`,
then `ionic serve`

```
Running 'serve:before' npm script before serve
> ionic-hello-world@ watch /Users/sober/ionic/preview
> ionic-app-scripts watch
[14:31:20]  ionic-app-scripts 0.0.23
[14:31:20]  watch started ...
[14:31:20]  build dev started ...
[14:31:20]  clean started ...
[14:31:20]  clean finished in 18 ms
[14:31:20]  copy started ...
[14:31:20]  typescript compiler started ...
[14:31:20]  lint started ...
[14:31:20]  copy finished in 73 ms
[14:31:20]  tslint: /Users/sober/ionic/preview/node_modules/tslint/lib/configuration.js:134


[14:31:20]  tslint:             throw new Error(("Invalid \"extends\" configuration value - could not require \"" + filePath + "\". ") +
            ^

Error: Invalid "extends" configuration value - could not require "tslint-ionic-rules". Review the Node lookup algorithm (https://nodejs.org/api/modules.html#modules_all_together) for the approximate method TSLint uses to find the referenced configuration file.
    at resolveConfigurationPath (/Users/sober/ionic/preview/node_modules/tslint/lib/configuration.js:134:19)
    at loadConfigurationFromPath (/Users/sober/ionic/preview/node_modules/tslint/lib/configuration.js:105:38)
    at Object.findConfiguration (/Users/sober/ionic/preview/node_modules/tslint/lib/configuration.js:47:12)
    at processFile (/Users/sober/ionic/preview/node_modules/tslint/lib/tslint-cli.js:131:41)
    at /Users/sober/ionic/preview/node_modules/tslint/lib/tslint-cli.js:177:74
    at Array.forEach (native)
    at Object.<anonymous> (/Users/sober/ionic/preview/node_modules/tslint/lib/tslint-cli.js:177:41)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)


[14:31:20]  lint finished in 330 ms
[14:31:22]  src/app/main.prod.ts(4,36): error TS2307: Cannot find module './app.module.ngfactory'.
[14:31:22]  typescript compiler ready in 2.75 s
[14:31:22]  bundle dev started ...
[14:31:28]  bundle dev finished in 5.62 s
[14:31:28]  sass started ...
[14:31:29]  sass finished in 1.16 s
[14:31:29]  build dev finished in 9.55 s
[14:31:29]  watch ready in 9.63 s
Running live reload server: http://localhost:35729
Watching: www/**/*, !www/lib/**/*
√ Running dev server:  http://localhost:8100
Ionic server commands, enter:
  restart or r to restart the client app from the root
  goto or g and a url to have the app navigate to the given url
  consolelogs or c to enable/disable console log output
  serverlogs or s to enable/disable server log output
  quit or q to shutdown the server and exit
```

**Comment by mhartington** [comment]
Should be good now.
